"""Renders the generated files (.generated/, systemd units) from config.yaml."""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Dict

import yaml

from .config import Config

REPO_DIR = Path(__file__).resolve().parent.parent
CONTAINER_HOME = "/home/agent"


def managed_settings(cfg: Config) -> Dict[str, Any]:
    settings: Dict[str, Any] = {"permissions": {"defaultMode": cfg.permission_mode}}
    if cfg.model:
        settings["model"] = cfg.model
    return settings


def compose(cfg: Config, user: str) -> Dict[str, Any]:
    volumes = [
        f"{cfg.state_dir}:{CONTAINER_HOME}",
        f"{cfg.workspace_dir}:/workspace",
        f"{cfg.inbox_dir}:/queue/inbox",
        f"{cfg.results_dir}:/queue/results:ro",
        f"{cfg.generated_dir / 'managed-settings.json'}:/etc/claude-code/managed-settings.json:ro",
    ]
    volumes += [f"{m.host}:{m.container}:{m.mode}" for m in cfg.mounts]

    env = {
        "SANDBOX_NAME": cfg.name,
        "HOME": CONTAINER_HOME,
        "HOSTCTL_QUEUE": "/queue",
        "DISABLE_AUTOUPDATER": "1",
        "GIT_AUTHOR_NAME": str(cfg.git["name"]),
        "GIT_COMMITTER_NAME": str(cfg.git["name"]),
        "GIT_AUTHOR_EMAIL": str(cfg.git["email"]),
        "GIT_COMMITTER_EMAIL": str(cfg.git["email"]),
    }
    if cfg.git["ssh_key"]:
        volumes.append(f"{cfg.git['ssh_key']}:/run/secrets/git_key:ro")
        env["GIT_SSH_COMMAND"] = (
            "ssh -i /run/secrets/git_key -o IdentitiesOnly=yes "
            "-o StrictHostKeyChecking=accept-new "
            f"-o UserKnownHostsFile={CONTAINER_HOME}/.ssh/known_hosts"
        )
    if user.split(":")[0] == "0":
        env["IS_SANDBOX"] = "1"
    env.update(cfg.container["environment"])

    service: Dict[str, Any] = {
        "build": {
            "context": str(REPO_DIR / "image"),
            "args": {
                "CLAUDE_CODE_VERSION": cfg.claude_code_version,
                "APT_PACKAGES": " ".join(cfg.container["apt_packages"]),
                "PYTHON_PACKAGES": " ".join(cfg.container["python_packages"]),
            },
        },
        "image": f"claude-sandbox-{cfg.name}:latest",
        "user": user,
        "init": True,
        "restart": "unless-stopped",
        "working_dir": "/workspace",
        "environment": env,
        "volumes": volumes,
        "tmpfs": ["/tmp"],
        "cap_drop": ["ALL"],
        "security_opt": ["no-new-privileges:true"],
    }
    if cfg.container["memory"]:
        service["mem_limit"] = str(cfg.container["memory"])
    if cfg.container["cpus"]:
        service["cpus"] = cfg.container["cpus"]
    return {"name": cfg.unit_prefix, "services": {"claude": service}}


def _quote(value: str) -> str:
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


def systemd_units(cfg: Config) -> Dict[str, str]:
    service_name = f"{cfg.unit_prefix}-broker.service"
    path_unit = (
        "[Unit]\n"
        f"Description=claude-sandbox {cfg.name}: watch the host action queue\n"
        "\n"
        "[Path]\n"
        f"DirectoryNotEmpty={cfg.requests_dir}\n"
        f"Unit={service_name}\n"
        "\n"
        "[Install]\n"
        "WantedBy=default.target\n"
    )
    exec_start = " ".join(_quote(p) for p in (
        sys.executable, REPO_DIR / "sandbox", "--config", cfg.path)) + " broker"
    service_unit = (
        "[Unit]\n"
        f"Description=claude-sandbox {cfg.name}: run queued host actions\n"
        "\n"
        "[Service]\n"
        "Type=oneshot\n"
        f"ExecStart={exec_start}\n"
    )
    return {
        f"{cfg.unit_prefix}-broker.path": path_unit,
        service_name: service_unit,
    }


def write_generated(cfg: Config, user: str) -> Path:
    cfg.generated_dir.mkdir(parents=True, exist_ok=True)
    (cfg.generated_dir / "managed-settings.json").write_text(
        json.dumps(managed_settings(cfg), indent=2) + "\n")
    compose_path = cfg.generated_dir / "compose.yaml"
    compose_path.write_text(
        "# Generated by ./sandbox from config.yaml. Do not edit.\n"
        + yaml.safe_dump(compose(cfg, user), sort_keys=False))
    return compose_path
